id: el_gamal
categories:
  - stream
  - substitution
cipher:
  encrypt:
    format: int
    params: &params
      - name: g
        type: prime
      - name: x
        type: int
      - name: mod
        type: prime
  decrypt:
    format: '(int,int)'
    params: *params