name: enigma
init:
- name: alphabet
  type: alphabet
cipher:
  encrypt: &encrypt
    format: str
    params: &params
      - name: rings
        type: dict(char){3,5}
      - name: reflector
        type: char
      - name: flip
        type: dict
  decrypt: *encrypt