uwsgi: &web
  module: app:app
  master: true
  processes: 5
  http-socket: 0.0.0.0:5050
  socket: cryptonite.sock
  chmod-sock: 660
  vaccum: true
  die-on-term: true
  enable-threads: true

app:
  default: &default
    web: *web
    max_file_size: 1073741824 #1Mb
  production:
    <<: *default
    debug: false
  development:
    <<: *default
    debug: true
    secret_key: some_secret