name: rsa
init:
- name: mod
  type: prime
cipher:
  encrypt:
    format: int
    params: &params
      - name: e
        type: int
  decrypt:
    format: int
    params:
      - name: d
        type: int
      - name: e
        type: int