id: elliptic
categories:
  - stream
  - substitution
init:
  - name: a
    type: int
  - name: b
    type: int
  - name: mod
    type: prime
  - name: p
    type: elliptic_point
  - name: d
    type: int
cipher:
  encrypt:
    format: int
    params:
      - name: q
        type: elliptic_point
      - name: rand
        type: '[int]'
  decrypt:
    format: (int,int)
    params:
eds:
  sign:
    format: int
    params:
      - name: G
        type: elliptic_point
      - name: k
        type: int
  check:
    format: int
    params:
      - name: Y
        type: elliptic_point
      - name: r
        type: int
      - name: s
        type: int