id: enigma
categories:
  - stream
  - substitution
rings: &rings
  1: EKMFLGDQVZNTOWYHXUSPAIBRCJ
  2: AJDKSIRUXBLHWTMCQGZNPYFVOE
  3: BDFHJLCPRTXVZNYEIWGAKMUSQO
  4: ESOVPZJAYQUIRHXLNFTGKDCMWB
  5: VZBRGITYUPSDNHLXAWMJQOFECK
  6: JPGVOUMFYQBENHZRDKASXLICTW
  7: NZJHGRCXMYSWBOUFAIVLPEKQDT
  8: FKQHTLXOCBJSPDZRAMEWNIUYGV
rotations: &rotations
  1: [Q]
  2: [E]
  3: [V]
  4: [J]
  5: [Z]
  6: [Z,M]
  7: [Z,M]
  8: [Z,M]
reflectors: &reflectors
  A: EJMZALYXVBWFCRQUONTSPIKHGD
  B: YRUHQSLDPXNGOKMIEBFZCWVJAT
  C: FVPJIAOYEDRZXWGCTKUQSBNMHL
  b: ENKQAUYWJICOPBLMDXZVFTHRGS
  c: RDOBJNTKVEHMLFCWZAXGYIPSUQ
  beta: LEYJVCNIXWPBQMDRTAKZGFUHOS
  gamma: FSOKANUERHMBTIYCWLQPZXVGJD
init:
  - name: keys
    type: regexp
    expr: '[a-z]{3,5}'
    default: 'ABC'
    required: true
  - name: rings
    type: regexp
    expr: '[1-8]{3,5}'
    default: '123'
    required: true
  - name: reflector
    type: select
    values:
      <<: *reflectors
    default: 'A'
    required: true
  - name: flip
    type: regexp
    expr: '([a-z][a-z])*'
cipher:
  encrypt: &encrypt
    format: str
  decrypt: *encrypt